/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the RegisterSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterSecretRequest{}

// RegisterSecretRequest struct for RegisterSecretRequest
type RegisterSecretRequest struct {
	Identifier int32 `json:"identifier"`
	AdditionalProperties map[string]interface{}
}

type _RegisterSecretRequest RegisterSecretRequest

// NewRegisterSecretRequest instantiates a new RegisterSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterSecretRequest(identifier int32) *RegisterSecretRequest {
	this := RegisterSecretRequest{}
	this.Identifier = identifier
	return &this
}

// NewRegisterSecretRequestWithDefaults instantiates a new RegisterSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterSecretRequestWithDefaults() *RegisterSecretRequest {
	this := RegisterSecretRequest{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *RegisterSecretRequest) GetIdentifier() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *RegisterSecretRequest) GetIdentifierOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *RegisterSecretRequest) SetIdentifier(v int32) {
	o.Identifier = v
}

func (o RegisterSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterSecretRequest) UnmarshalJSON(bytes []byte) (err error) {
	varRegisterSecretRequest := _RegisterSecretRequest{}

	if err = json.Unmarshal(bytes, &varRegisterSecretRequest); err == nil {
		*o = RegisterSecretRequest(varRegisterSecretRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterSecretRequest struct {
	value *RegisterSecretRequest
	isSet bool
}

func (v NullableRegisterSecretRequest) Get() *RegisterSecretRequest {
	return v.value
}

func (v *NullableRegisterSecretRequest) Set(val *RegisterSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterSecretRequest(val *RegisterSecretRequest) *NullableRegisterSecretRequest {
	return &NullableRegisterSecretRequest{value: val, isSet: true}
}

func (v NullableRegisterSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


