/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ApplicationPAMCredentialProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationPAMCredentialProfile{}

// ApplicationPAMCredentialProfile This model describes all PAM Credential Profile properties
type ApplicationPAMCredentialProfile struct {
	// Profile ID generated by senhasegura
	Id int32 `json:"id"`
	// Profile name registered on senhasegura PAM module
	Identifier string `json:"identifier"`
	// Target asset to execute this profile
	Target string `json:"target"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationPAMCredentialProfile ApplicationPAMCredentialProfile

// NewApplicationPAMCredentialProfile instantiates a new ApplicationPAMCredentialProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationPAMCredentialProfile(id int32, identifier string, target string) *ApplicationPAMCredentialProfile {
	this := ApplicationPAMCredentialProfile{}
	this.Id = id
	this.Identifier = identifier
	this.Target = target
	return &this
}

// NewApplicationPAMCredentialProfileWithDefaults instantiates a new ApplicationPAMCredentialProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationPAMCredentialProfileWithDefaults() *ApplicationPAMCredentialProfile {
	this := ApplicationPAMCredentialProfile{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationPAMCredentialProfile) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationPAMCredentialProfile) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationPAMCredentialProfile) SetId(v int32) {
	o.Id = v
}

// GetIdentifier returns the Identifier field value
func (o *ApplicationPAMCredentialProfile) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ApplicationPAMCredentialProfile) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ApplicationPAMCredentialProfile) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTarget returns the Target field value
func (o *ApplicationPAMCredentialProfile) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ApplicationPAMCredentialProfile) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ApplicationPAMCredentialProfile) SetTarget(v string) {
	o.Target = v
}

func (o ApplicationPAMCredentialProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationPAMCredentialProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["identifier"] = o.Identifier
	toSerialize["target"] = o.Target

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationPAMCredentialProfile) UnmarshalJSON(bytes []byte) (err error) {
	varApplicationPAMCredentialProfile := _ApplicationPAMCredentialProfile{}

	if err = json.Unmarshal(bytes, &varApplicationPAMCredentialProfile); err == nil {
		*o = ApplicationPAMCredentialProfile(varApplicationPAMCredentialProfile)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "target")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationPAMCredentialProfile struct {
	value *ApplicationPAMCredentialProfile
	isSet bool
}

func (v NullableApplicationPAMCredentialProfile) Get() *ApplicationPAMCredentialProfile {
	return v.value
}

func (v *NullableApplicationPAMCredentialProfile) Set(val *ApplicationPAMCredentialProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationPAMCredentialProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationPAMCredentialProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationPAMCredentialProfile(val *ApplicationPAMCredentialProfile) *NullableApplicationPAMCredentialProfile {
	return &NullableApplicationPAMCredentialProfile{value: val, isSet: true}
}

func (v NullableApplicationPAMCredentialProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationPAMCredentialProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


