/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ApplicationPAMCredentialProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationPAMCredentialProfileRequest{}

// ApplicationPAMCredentialProfileRequest This model describes all PAM Credential Profile properties
type ApplicationPAMCredentialProfileRequest struct {
	// Profile name registered on senhasegura PAM module
	Identifier string `json:"identifier"`
	// Target asset to execute this profile
	Target string `json:"target"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationPAMCredentialProfileRequest ApplicationPAMCredentialProfileRequest

// NewApplicationPAMCredentialProfileRequest instantiates a new ApplicationPAMCredentialProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationPAMCredentialProfileRequest(identifier string, target string) *ApplicationPAMCredentialProfileRequest {
	this := ApplicationPAMCredentialProfileRequest{}
	this.Identifier = identifier
	this.Target = target
	return &this
}

// NewApplicationPAMCredentialProfileRequestWithDefaults instantiates a new ApplicationPAMCredentialProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationPAMCredentialProfileRequestWithDefaults() *ApplicationPAMCredentialProfileRequest {
	this := ApplicationPAMCredentialProfileRequest{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *ApplicationPAMCredentialProfileRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ApplicationPAMCredentialProfileRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ApplicationPAMCredentialProfileRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTarget returns the Target field value
func (o *ApplicationPAMCredentialProfileRequest) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ApplicationPAMCredentialProfileRequest) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ApplicationPAMCredentialProfileRequest) SetTarget(v string) {
	o.Target = v
}

func (o ApplicationPAMCredentialProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationPAMCredentialProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["target"] = o.Target

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationPAMCredentialProfileRequest) UnmarshalJSON(bytes []byte) (err error) {
	varApplicationPAMCredentialProfileRequest := _ApplicationPAMCredentialProfileRequest{}

	if err = json.Unmarshal(bytes, &varApplicationPAMCredentialProfileRequest); err == nil {
		*o = ApplicationPAMCredentialProfileRequest(varApplicationPAMCredentialProfileRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "identifier")
		delete(additionalProperties, "target")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationPAMCredentialProfileRequest struct {
	value *ApplicationPAMCredentialProfileRequest
	isSet bool
}

func (v NullableApplicationPAMCredentialProfileRequest) Get() *ApplicationPAMCredentialProfileRequest {
	return v.value
}

func (v *NullableApplicationPAMCredentialProfileRequest) Set(val *ApplicationPAMCredentialProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationPAMCredentialProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationPAMCredentialProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationPAMCredentialProfileRequest(val *ApplicationPAMCredentialProfileRequest) *NullableApplicationPAMCredentialProfileRequest {
	return &NullableApplicationPAMCredentialProfileRequest{value: val, isSet: true}
}

func (v NullableApplicationPAMCredentialProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationPAMCredentialProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


