/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the ApplicationCloudCredentialProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationCloudCredentialProfile{}

// ApplicationCloudCredentialProfile This model describes all Cloud Credential Profile properties
type ApplicationCloudCredentialProfile struct {
	// Profile ID generated by senhasegura
	Id int32 `json:"id"`
	// Profile name registered on senhasegura Cloud IAM module
	Identifier string `json:"identifier"`
	AdditionalProperties map[string]interface{}
}

type _ApplicationCloudCredentialProfile ApplicationCloudCredentialProfile

// NewApplicationCloudCredentialProfile instantiates a new ApplicationCloudCredentialProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCloudCredentialProfile(id int32, identifier string) *ApplicationCloudCredentialProfile {
	this := ApplicationCloudCredentialProfile{}
	this.Id = id
	this.Identifier = identifier
	return &this
}

// NewApplicationCloudCredentialProfileWithDefaults instantiates a new ApplicationCloudCredentialProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCloudCredentialProfileWithDefaults() *ApplicationCloudCredentialProfile {
	this := ApplicationCloudCredentialProfile{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationCloudCredentialProfile) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationCloudCredentialProfile) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationCloudCredentialProfile) SetId(v int32) {
	o.Id = v
}

// GetIdentifier returns the Identifier field value
func (o *ApplicationCloudCredentialProfile) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ApplicationCloudCredentialProfile) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ApplicationCloudCredentialProfile) SetIdentifier(v string) {
	o.Identifier = v
}

func (o ApplicationCloudCredentialProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationCloudCredentialProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["identifier"] = o.Identifier

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApplicationCloudCredentialProfile) UnmarshalJSON(bytes []byte) (err error) {
	varApplicationCloudCredentialProfile := _ApplicationCloudCredentialProfile{}

	if err = json.Unmarshal(bytes, &varApplicationCloudCredentialProfile); err == nil {
		*o = ApplicationCloudCredentialProfile(varApplicationCloudCredentialProfile)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "identifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApplicationCloudCredentialProfile struct {
	value *ApplicationCloudCredentialProfile
	isSet bool
}

func (v NullableApplicationCloudCredentialProfile) Get() *ApplicationCloudCredentialProfile {
	return v.value
}

func (v *NullableApplicationCloudCredentialProfile) Set(val *ApplicationCloudCredentialProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCloudCredentialProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCloudCredentialProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCloudCredentialProfile(val *ApplicationCloudCredentialProfile) *NullableApplicationCloudCredentialProfile {
	return &NullableApplicationCloudCredentialProfile{value: val, isSet: true}
}

func (v NullableApplicationCloudCredentialProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCloudCredentialProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


