/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SecretCloudCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretCloudCredentialRequest{}

// SecretCloudCredentialRequest This model describes all Cloud Credential properties
type SecretCloudCredentialRequest struct {
	Id int32 `json:"id"`
	AccessKeyIdLabel *string `json:"access_key_id_label,omitempty"`
	SecretAccessKeyLabel *string `json:"secret_access_key_label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SecretCloudCredentialRequest SecretCloudCredentialRequest

// NewSecretCloudCredentialRequest instantiates a new SecretCloudCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretCloudCredentialRequest(id int32) *SecretCloudCredentialRequest {
	this := SecretCloudCredentialRequest{}
	this.Id = id
	return &this
}

// NewSecretCloudCredentialRequestWithDefaults instantiates a new SecretCloudCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretCloudCredentialRequestWithDefaults() *SecretCloudCredentialRequest {
	this := SecretCloudCredentialRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SecretCloudCredentialRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretCloudCredentialRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretCloudCredentialRequest) SetId(v int32) {
	o.Id = v
}

// GetAccessKeyIdLabel returns the AccessKeyIdLabel field value if set, zero value otherwise.
func (o *SecretCloudCredentialRequest) GetAccessKeyIdLabel() string {
	if o == nil || isNil(o.AccessKeyIdLabel) {
		var ret string
		return ret
	}
	return *o.AccessKeyIdLabel
}

// GetAccessKeyIdLabelOk returns a tuple with the AccessKeyIdLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretCloudCredentialRequest) GetAccessKeyIdLabelOk() (*string, bool) {
	if o == nil || isNil(o.AccessKeyIdLabel) {
		return nil, false
	}
	return o.AccessKeyIdLabel, true
}

// HasAccessKeyIdLabel returns a boolean if a field has been set.
func (o *SecretCloudCredentialRequest) HasAccessKeyIdLabel() bool {
	if o != nil && !isNil(o.AccessKeyIdLabel) {
		return true
	}

	return false
}

// SetAccessKeyIdLabel gets a reference to the given string and assigns it to the AccessKeyIdLabel field.
func (o *SecretCloudCredentialRequest) SetAccessKeyIdLabel(v string) {
	o.AccessKeyIdLabel = &v
}

// GetSecretAccessKeyLabel returns the SecretAccessKeyLabel field value if set, zero value otherwise.
func (o *SecretCloudCredentialRequest) GetSecretAccessKeyLabel() string {
	if o == nil || isNil(o.SecretAccessKeyLabel) {
		var ret string
		return ret
	}
	return *o.SecretAccessKeyLabel
}

// GetSecretAccessKeyLabelOk returns a tuple with the SecretAccessKeyLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretCloudCredentialRequest) GetSecretAccessKeyLabelOk() (*string, bool) {
	if o == nil || isNil(o.SecretAccessKeyLabel) {
		return nil, false
	}
	return o.SecretAccessKeyLabel, true
}

// HasSecretAccessKeyLabel returns a boolean if a field has been set.
func (o *SecretCloudCredentialRequest) HasSecretAccessKeyLabel() bool {
	if o != nil && !isNil(o.SecretAccessKeyLabel) {
		return true
	}

	return false
}

// SetSecretAccessKeyLabel gets a reference to the given string and assigns it to the SecretAccessKeyLabel field.
func (o *SecretCloudCredentialRequest) SetSecretAccessKeyLabel(v string) {
	o.SecretAccessKeyLabel = &v
}

func (o SecretCloudCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretCloudCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !isNil(o.AccessKeyIdLabel) {
		toSerialize["access_key_id_label"] = o.AccessKeyIdLabel
	}
	if !isNil(o.SecretAccessKeyLabel) {
		toSerialize["secret_access_key_label"] = o.SecretAccessKeyLabel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretCloudCredentialRequest) UnmarshalJSON(bytes []byte) (err error) {
	varSecretCloudCredentialRequest := _SecretCloudCredentialRequest{}

	if err = json.Unmarshal(bytes, &varSecretCloudCredentialRequest); err == nil {
		*o = SecretCloudCredentialRequest(varSecretCloudCredentialRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "access_key_id_label")
		delete(additionalProperties, "secret_access_key_label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretCloudCredentialRequest struct {
	value *SecretCloudCredentialRequest
	isSet bool
}

func (v NullableSecretCloudCredentialRequest) Get() *SecretCloudCredentialRequest {
	return v.value
}

func (v *NullableSecretCloudCredentialRequest) Set(val *SecretCloudCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretCloudCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretCloudCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretCloudCredentialRequest(val *SecretCloudCredentialRequest) *NullableSecretCloudCredentialRequest {
	return &NullableSecretCloudCredentialRequest{value: val, isSet: true}
}

func (v NullableSecretCloudCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretCloudCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


