/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SecretPAMEphemeralCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretPAMEphemeralCredential{}

// SecretPAMEphemeralCredential This model describes all PAM Credential properties
type SecretPAMEphemeralCredential struct {
	// PAM credential ID generated by senhasegura
	Id int32 `json:"id"`
	Ttl int32 `json:"ttl"`
	// PAM credential username
	Username string `json:"username"`
	// PAM credential password
	Password string `json:"password"`
	// PAM credential additional information, such as database instances
	AdditionalInformation *string `json:"additional_information,omitempty"`
	Type *string `json:"type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Device SecretPAMDevice `json:"device"`
	AdditionalProperties map[string]interface{}
}

type _SecretPAMEphemeralCredential SecretPAMEphemeralCredential

// NewSecretPAMEphemeralCredential instantiates a new SecretPAMEphemeralCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretPAMEphemeralCredential(id int32, ttl int32, username string, password string, device SecretPAMDevice) *SecretPAMEphemeralCredential {
	this := SecretPAMEphemeralCredential{}
	this.Id = id
	this.Ttl = ttl
	this.Username = username
	this.Password = password
	this.Device = device
	return &this
}

// NewSecretPAMEphemeralCredentialWithDefaults instantiates a new SecretPAMEphemeralCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretPAMEphemeralCredentialWithDefaults() *SecretPAMEphemeralCredential {
	this := SecretPAMEphemeralCredential{}
	return &this
}

// GetId returns the Id field value
func (o *SecretPAMEphemeralCredential) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretPAMEphemeralCredential) SetId(v int32) {
	o.Id = v
}

// GetTtl returns the Ttl field value
func (o *SecretPAMEphemeralCredential) GetTtl() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetTtlOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ttl, true
}

// SetTtl sets field value
func (o *SecretPAMEphemeralCredential) SetTtl(v int32) {
	o.Ttl = v
}

// GetUsername returns the Username field value
func (o *SecretPAMEphemeralCredential) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SecretPAMEphemeralCredential) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *SecretPAMEphemeralCredential) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SecretPAMEphemeralCredential) SetPassword(v string) {
	o.Password = v
}

// GetAdditionalInformation returns the AdditionalInformation field value if set, zero value otherwise.
func (o *SecretPAMEphemeralCredential) GetAdditionalInformation() string {
	if o == nil || isNil(o.AdditionalInformation) {
		var ret string
		return ret
	}
	return *o.AdditionalInformation
}

// GetAdditionalInformationOk returns a tuple with the AdditionalInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetAdditionalInformationOk() (*string, bool) {
	if o == nil || isNil(o.AdditionalInformation) {
		return nil, false
	}
	return o.AdditionalInformation, true
}

// HasAdditionalInformation returns a boolean if a field has been set.
func (o *SecretPAMEphemeralCredential) HasAdditionalInformation() bool {
	if o != nil && !isNil(o.AdditionalInformation) {
		return true
	}

	return false
}

// SetAdditionalInformation gets a reference to the given string and assigns it to the AdditionalInformation field.
func (o *SecretPAMEphemeralCredential) SetAdditionalInformation(v string) {
	o.AdditionalInformation = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SecretPAMEphemeralCredential) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SecretPAMEphemeralCredential) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SecretPAMEphemeralCredential) SetType(v string) {
	o.Type = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *SecretPAMEphemeralCredential) GetDomain() string {
	if o == nil || isNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetDomainOk() (*string, bool) {
	if o == nil || isNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *SecretPAMEphemeralCredential) HasDomain() bool {
	if o != nil && !isNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *SecretPAMEphemeralCredential) SetDomain(v string) {
	o.Domain = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SecretPAMEphemeralCredential) GetTags() []string {
	if o == nil || isNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetTagsOk() ([]string, bool) {
	if o == nil || isNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SecretPAMEphemeralCredential) HasTags() bool {
	if o != nil && !isNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SecretPAMEphemeralCredential) SetTags(v []string) {
	o.Tags = v
}

// GetDevice returns the Device field value
func (o *SecretPAMEphemeralCredential) GetDevice() SecretPAMDevice {
	if o == nil {
		var ret SecretPAMDevice
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *SecretPAMEphemeralCredential) GetDeviceOk() (*SecretPAMDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *SecretPAMEphemeralCredential) SetDevice(v SecretPAMDevice) {
	o.Device = v
}

func (o SecretPAMEphemeralCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretPAMEphemeralCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["ttl"] = o.Ttl
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	if !isNil(o.AdditionalInformation) {
		toSerialize["additional_information"] = o.AdditionalInformation
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !isNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["device"] = o.Device

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretPAMEphemeralCredential) UnmarshalJSON(bytes []byte) (err error) {
	varSecretPAMEphemeralCredential := _SecretPAMEphemeralCredential{}

	if err = json.Unmarshal(bytes, &varSecretPAMEphemeralCredential); err == nil {
		*o = SecretPAMEphemeralCredential(varSecretPAMEphemeralCredential)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ttl")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "additional_information")
		delete(additionalProperties, "type")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "device")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretPAMEphemeralCredential struct {
	value *SecretPAMEphemeralCredential
	isSet bool
}

func (v NullableSecretPAMEphemeralCredential) Get() *SecretPAMEphemeralCredential {
	return v.value
}

func (v *NullableSecretPAMEphemeralCredential) Set(val *SecretPAMEphemeralCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretPAMEphemeralCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretPAMEphemeralCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretPAMEphemeralCredential(val *SecretPAMEphemeralCredential) *NullableSecretPAMEphemeralCredential {
	return &NullableSecretPAMEphemeralCredential{value: val, isSet: true}
}

func (v NullableSecretPAMEphemeralCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretPAMEphemeralCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


