/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SecretPAMSSHKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretPAMSSHKeyRequest{}

// SecretPAMSSHKeyRequest This model describes all PAM Credential properties
type SecretPAMSSHKeyRequest struct {
	// PAM credential ID generated by senhasegura
	Id int32 `json:"id"`
	UsernameLabel *string `json:"username_label,omitempty"`
	PasswordLabel *string `json:"password_label,omitempty"`
	PublicKeyLabel *string `json:"public_key_label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SecretPAMSSHKeyRequest SecretPAMSSHKeyRequest

// NewSecretPAMSSHKeyRequest instantiates a new SecretPAMSSHKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretPAMSSHKeyRequest(id int32) *SecretPAMSSHKeyRequest {
	this := SecretPAMSSHKeyRequest{}
	this.Id = id
	return &this
}

// NewSecretPAMSSHKeyRequestWithDefaults instantiates a new SecretPAMSSHKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretPAMSSHKeyRequestWithDefaults() *SecretPAMSSHKeyRequest {
	this := SecretPAMSSHKeyRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SecretPAMSSHKeyRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretPAMSSHKeyRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretPAMSSHKeyRequest) SetId(v int32) {
	o.Id = v
}

// GetUsernameLabel returns the UsernameLabel field value if set, zero value otherwise.
func (o *SecretPAMSSHKeyRequest) GetUsernameLabel() string {
	if o == nil || isNil(o.UsernameLabel) {
		var ret string
		return ret
	}
	return *o.UsernameLabel
}

// GetUsernameLabelOk returns a tuple with the UsernameLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMSSHKeyRequest) GetUsernameLabelOk() (*string, bool) {
	if o == nil || isNil(o.UsernameLabel) {
		return nil, false
	}
	return o.UsernameLabel, true
}

// HasUsernameLabel returns a boolean if a field has been set.
func (o *SecretPAMSSHKeyRequest) HasUsernameLabel() bool {
	if o != nil && !isNil(o.UsernameLabel) {
		return true
	}

	return false
}

// SetUsernameLabel gets a reference to the given string and assigns it to the UsernameLabel field.
func (o *SecretPAMSSHKeyRequest) SetUsernameLabel(v string) {
	o.UsernameLabel = &v
}

// GetPasswordLabel returns the PasswordLabel field value if set, zero value otherwise.
func (o *SecretPAMSSHKeyRequest) GetPasswordLabel() string {
	if o == nil || isNil(o.PasswordLabel) {
		var ret string
		return ret
	}
	return *o.PasswordLabel
}

// GetPasswordLabelOk returns a tuple with the PasswordLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMSSHKeyRequest) GetPasswordLabelOk() (*string, bool) {
	if o == nil || isNil(o.PasswordLabel) {
		return nil, false
	}
	return o.PasswordLabel, true
}

// HasPasswordLabel returns a boolean if a field has been set.
func (o *SecretPAMSSHKeyRequest) HasPasswordLabel() bool {
	if o != nil && !isNil(o.PasswordLabel) {
		return true
	}

	return false
}

// SetPasswordLabel gets a reference to the given string and assigns it to the PasswordLabel field.
func (o *SecretPAMSSHKeyRequest) SetPasswordLabel(v string) {
	o.PasswordLabel = &v
}

// GetPublicKeyLabel returns the PublicKeyLabel field value if set, zero value otherwise.
func (o *SecretPAMSSHKeyRequest) GetPublicKeyLabel() string {
	if o == nil || isNil(o.PublicKeyLabel) {
		var ret string
		return ret
	}
	return *o.PublicKeyLabel
}

// GetPublicKeyLabelOk returns a tuple with the PublicKeyLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMSSHKeyRequest) GetPublicKeyLabelOk() (*string, bool) {
	if o == nil || isNil(o.PublicKeyLabel) {
		return nil, false
	}
	return o.PublicKeyLabel, true
}

// HasPublicKeyLabel returns a boolean if a field has been set.
func (o *SecretPAMSSHKeyRequest) HasPublicKeyLabel() bool {
	if o != nil && !isNil(o.PublicKeyLabel) {
		return true
	}

	return false
}

// SetPublicKeyLabel gets a reference to the given string and assigns it to the PublicKeyLabel field.
func (o *SecretPAMSSHKeyRequest) SetPublicKeyLabel(v string) {
	o.PublicKeyLabel = &v
}

func (o SecretPAMSSHKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretPAMSSHKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !isNil(o.UsernameLabel) {
		toSerialize["username_label"] = o.UsernameLabel
	}
	if !isNil(o.PasswordLabel) {
		toSerialize["password_label"] = o.PasswordLabel
	}
	if !isNil(o.PublicKeyLabel) {
		toSerialize["public_key_label"] = o.PublicKeyLabel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretPAMSSHKeyRequest) UnmarshalJSON(bytes []byte) (err error) {
	varSecretPAMSSHKeyRequest := _SecretPAMSSHKeyRequest{}

	if err = json.Unmarshal(bytes, &varSecretPAMSSHKeyRequest); err == nil {
		*o = SecretPAMSSHKeyRequest(varSecretPAMSSHKeyRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "username_label")
		delete(additionalProperties, "password_label")
		delete(additionalProperties, "public_key_label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretPAMSSHKeyRequest struct {
	value *SecretPAMSSHKeyRequest
	isSet bool
}

func (v NullableSecretPAMSSHKeyRequest) Get() *SecretPAMSSHKeyRequest {
	return v.value
}

func (v *NullableSecretPAMSSHKeyRequest) Set(val *SecretPAMSSHKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretPAMSSHKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretPAMSSHKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretPAMSSHKeyRequest(val *SecretPAMSSHKeyRequest) *NullableSecretPAMSSHKeyRequest {
	return &NullableSecretPAMSSHKeyRequest{value: val, isSet: true}
}

func (v NullableSecretPAMSSHKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretPAMSSHKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


