/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SecretPAMCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretPAMCredentialRequest{}

// SecretPAMCredentialRequest This model describes all PAM Credential properties
type SecretPAMCredentialRequest struct {
	Id int32 `json:"id"`
	UsernameLabel *string `json:"username_label,omitempty"`
	PasswordLabel *string `json:"password_label,omitempty"`
	AdditionalInformationLabel *string `json:"additional_information_label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SecretPAMCredentialRequest SecretPAMCredentialRequest

// NewSecretPAMCredentialRequest instantiates a new SecretPAMCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretPAMCredentialRequest(id int32) *SecretPAMCredentialRequest {
	this := SecretPAMCredentialRequest{}
	this.Id = id
	return &this
}

// NewSecretPAMCredentialRequestWithDefaults instantiates a new SecretPAMCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretPAMCredentialRequestWithDefaults() *SecretPAMCredentialRequest {
	this := SecretPAMCredentialRequest{}
	return &this
}

// GetId returns the Id field value
func (o *SecretPAMCredentialRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretPAMCredentialRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretPAMCredentialRequest) SetId(v int32) {
	o.Id = v
}

// GetUsernameLabel returns the UsernameLabel field value if set, zero value otherwise.
func (o *SecretPAMCredentialRequest) GetUsernameLabel() string {
	if o == nil || isNil(o.UsernameLabel) {
		var ret string
		return ret
	}
	return *o.UsernameLabel
}

// GetUsernameLabelOk returns a tuple with the UsernameLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredentialRequest) GetUsernameLabelOk() (*string, bool) {
	if o == nil || isNil(o.UsernameLabel) {
		return nil, false
	}
	return o.UsernameLabel, true
}

// HasUsernameLabel returns a boolean if a field has been set.
func (o *SecretPAMCredentialRequest) HasUsernameLabel() bool {
	if o != nil && !isNil(o.UsernameLabel) {
		return true
	}

	return false
}

// SetUsernameLabel gets a reference to the given string and assigns it to the UsernameLabel field.
func (o *SecretPAMCredentialRequest) SetUsernameLabel(v string) {
	o.UsernameLabel = &v
}

// GetPasswordLabel returns the PasswordLabel field value if set, zero value otherwise.
func (o *SecretPAMCredentialRequest) GetPasswordLabel() string {
	if o == nil || isNil(o.PasswordLabel) {
		var ret string
		return ret
	}
	return *o.PasswordLabel
}

// GetPasswordLabelOk returns a tuple with the PasswordLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredentialRequest) GetPasswordLabelOk() (*string, bool) {
	if o == nil || isNil(o.PasswordLabel) {
		return nil, false
	}
	return o.PasswordLabel, true
}

// HasPasswordLabel returns a boolean if a field has been set.
func (o *SecretPAMCredentialRequest) HasPasswordLabel() bool {
	if o != nil && !isNil(o.PasswordLabel) {
		return true
	}

	return false
}

// SetPasswordLabel gets a reference to the given string and assigns it to the PasswordLabel field.
func (o *SecretPAMCredentialRequest) SetPasswordLabel(v string) {
	o.PasswordLabel = &v
}

// GetAdditionalInformationLabel returns the AdditionalInformationLabel field value if set, zero value otherwise.
func (o *SecretPAMCredentialRequest) GetAdditionalInformationLabel() string {
	if o == nil || isNil(o.AdditionalInformationLabel) {
		var ret string
		return ret
	}
	return *o.AdditionalInformationLabel
}

// GetAdditionalInformationLabelOk returns a tuple with the AdditionalInformationLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredentialRequest) GetAdditionalInformationLabelOk() (*string, bool) {
	if o == nil || isNil(o.AdditionalInformationLabel) {
		return nil, false
	}
	return o.AdditionalInformationLabel, true
}

// HasAdditionalInformationLabel returns a boolean if a field has been set.
func (o *SecretPAMCredentialRequest) HasAdditionalInformationLabel() bool {
	if o != nil && !isNil(o.AdditionalInformationLabel) {
		return true
	}

	return false
}

// SetAdditionalInformationLabel gets a reference to the given string and assigns it to the AdditionalInformationLabel field.
func (o *SecretPAMCredentialRequest) SetAdditionalInformationLabel(v string) {
	o.AdditionalInformationLabel = &v
}

func (o SecretPAMCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretPAMCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !isNil(o.UsernameLabel) {
		toSerialize["username_label"] = o.UsernameLabel
	}
	if !isNil(o.PasswordLabel) {
		toSerialize["password_label"] = o.PasswordLabel
	}
	if !isNil(o.AdditionalInformationLabel) {
		toSerialize["additional_information_label"] = o.AdditionalInformationLabel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretPAMCredentialRequest) UnmarshalJSON(bytes []byte) (err error) {
	varSecretPAMCredentialRequest := _SecretPAMCredentialRequest{}

	if err = json.Unmarshal(bytes, &varSecretPAMCredentialRequest); err == nil {
		*o = SecretPAMCredentialRequest(varSecretPAMCredentialRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "username_label")
		delete(additionalProperties, "password_label")
		delete(additionalProperties, "additional_information_label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretPAMCredentialRequest struct {
	value *SecretPAMCredentialRequest
	isSet bool
}

func (v NullableSecretPAMCredentialRequest) Get() *SecretPAMCredentialRequest {
	return v.value
}

func (v *NullableSecretPAMCredentialRequest) Set(val *SecretPAMCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretPAMCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretPAMCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretPAMCredentialRequest(val *SecretPAMCredentialRequest) *NullableSecretPAMCredentialRequest {
	return &NullableSecretPAMCredentialRequest{value: val, isSet: true}
}

func (v NullableSecretPAMCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretPAMCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


