/*
senhasegura DSM API Reference

This is a senhasegura new API design

API version: 2.0.22
Contact: egoncalves@senhasegura.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the SecretPAMCredential type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretPAMCredential{}

// SecretPAMCredential This model describes all PAM Credential properties
type SecretPAMCredential struct {
	// PAM credential ID generated by senhasegura
	Id int32 `json:"id"`
	// PAM credential username
	Username string `json:"username"`
	// PAM credential password
	Password string `json:"password"`
	// PAM credential additional information, such as database instances
	AdditionalInformation *string `json:"additional_information,omitempty"`
	Type *string `json:"type,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Device SecretPAMDevice `json:"device"`
	AdditionalProperties map[string]interface{}
}

type _SecretPAMCredential SecretPAMCredential

// NewSecretPAMCredential instantiates a new SecretPAMCredential object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretPAMCredential(id int32, username string, password string, device SecretPAMDevice) *SecretPAMCredential {
	this := SecretPAMCredential{}
	this.Id = id
	this.Username = username
	this.Password = password
	this.Device = device
	return &this
}

// NewSecretPAMCredentialWithDefaults instantiates a new SecretPAMCredential object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretPAMCredentialWithDefaults() *SecretPAMCredential {
	this := SecretPAMCredential{}
	return &this
}

// GetId returns the Id field value
func (o *SecretPAMCredential) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SecretPAMCredential) SetId(v int32) {
	o.Id = v
}

// GetUsername returns the Username field value
func (o *SecretPAMCredential) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *SecretPAMCredential) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *SecretPAMCredential) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *SecretPAMCredential) SetPassword(v string) {
	o.Password = v
}

// GetAdditionalInformation returns the AdditionalInformation field value if set, zero value otherwise.
func (o *SecretPAMCredential) GetAdditionalInformation() string {
	if o == nil || isNil(o.AdditionalInformation) {
		var ret string
		return ret
	}
	return *o.AdditionalInformation
}

// GetAdditionalInformationOk returns a tuple with the AdditionalInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetAdditionalInformationOk() (*string, bool) {
	if o == nil || isNil(o.AdditionalInformation) {
		return nil, false
	}
	return o.AdditionalInformation, true
}

// HasAdditionalInformation returns a boolean if a field has been set.
func (o *SecretPAMCredential) HasAdditionalInformation() bool {
	if o != nil && !isNil(o.AdditionalInformation) {
		return true
	}

	return false
}

// SetAdditionalInformation gets a reference to the given string and assigns it to the AdditionalInformation field.
func (o *SecretPAMCredential) SetAdditionalInformation(v string) {
	o.AdditionalInformation = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SecretPAMCredential) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SecretPAMCredential) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SecretPAMCredential) SetType(v string) {
	o.Type = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *SecretPAMCredential) GetDomain() string {
	if o == nil || isNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetDomainOk() (*string, bool) {
	if o == nil || isNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *SecretPAMCredential) HasDomain() bool {
	if o != nil && !isNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *SecretPAMCredential) SetDomain(v string) {
	o.Domain = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SecretPAMCredential) GetTags() []string {
	if o == nil || isNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetTagsOk() ([]string, bool) {
	if o == nil || isNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SecretPAMCredential) HasTags() bool {
	if o != nil && !isNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SecretPAMCredential) SetTags(v []string) {
	o.Tags = v
}

// GetDevice returns the Device field value
func (o *SecretPAMCredential) GetDevice() SecretPAMDevice {
	if o == nil {
		var ret SecretPAMDevice
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *SecretPAMCredential) GetDeviceOk() (*SecretPAMDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *SecretPAMCredential) SetDevice(v SecretPAMDevice) {
	o.Device = v
}

func (o SecretPAMCredential) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretPAMCredential) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password
	if !isNil(o.AdditionalInformation) {
		toSerialize["additional_information"] = o.AdditionalInformation
	}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !isNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["device"] = o.Device

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SecretPAMCredential) UnmarshalJSON(bytes []byte) (err error) {
	varSecretPAMCredential := _SecretPAMCredential{}

	if err = json.Unmarshal(bytes, &varSecretPAMCredential); err == nil {
		*o = SecretPAMCredential(varSecretPAMCredential)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		delete(additionalProperties, "additional_information")
		delete(additionalProperties, "type")
		delete(additionalProperties, "domain")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "device")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSecretPAMCredential struct {
	value *SecretPAMCredential
	isSet bool
}

func (v NullableSecretPAMCredential) Get() *SecretPAMCredential {
	return v.value
}

func (v *NullableSecretPAMCredential) Set(val *SecretPAMCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretPAMCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretPAMCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretPAMCredential(val *SecretPAMCredential) *NullableSecretPAMCredential {
	return &NullableSecretPAMCredential{value: val, isSet: true}
}

func (v NullableSecretPAMCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretPAMCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


